# Generated by Django 3.2.12 on 2023-04-12 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('impact_rank', models.IntegerField()),
                ('openness_rank', models.IntegerField()),
                ('global_rank', models.IntegerField()),
            ],
        ),
    ]
